# Site settings
title: Marcin Mazurek
name: Marcin Mazurek
email: https://pl.linkedin.com/in/mmazurek/
description: Product, technology, and curiosity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://marcinmazurek.com" # the base hostname & protocol for your site
twitter_username: mazuchna
github_username:  mazek
linkedin_username: mmazurek
goodreads_url: "https://www.goodreads.com/review/list/39585864"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
