# Site settings
title: marcinmazurek.com
email: https://pl.linkedin.com/in/mmazurek/
description: > # this means to ignore newlines until "baseurl:"
    Just a simple classic hompage:)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcinmazurek.com" # the base hostname & protocol for your site
twitter_username: mazuchna
github_username:  mazek
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
